DINO_MODELS = {
    'GDINO-TINY': 'IDEA-Research/grounding-dino-tiny',
    'GDINO-BASE': 'IDEA-Research/grounding-dino-base',
}

OWL_MODELS = {
    'OWLVIT-BASE-16':       'google/owlvit-base-patch16',
    'OWLVIT-BASE-32':       'google/owlvit-base-patch32',
    'OWLVIT-LARGE':         'google/owlvit-large-patch14',
    'OWL2-BASE':            'google/owlv2-base-patch16',
    'OWL2-BASE-ENSEMBLE':   'google/owlv2-base-patch16-ensemble',
    'OWL2-BASE-FINETUNED':  'google/owlv2-base-patch16-finetuned',
    'OWL2-LARGE':           'google/owlv2-large-patch14',
    'OWL2-LARGE-ENSEMBLE':  'google/owlv2-large-patch14-ensemble',
    'OWL2-LARGE-FINETUNED': 'google/owlv2-large-patch14-finetuned',
}

YOLO_WORLD_MODELS = {
    'YOLO-S-WORLD':    'checkpoints/yolov8s-world.pt',
    'YOLO-M-WORLD':    'checkpoints/yolov8m-world.pt',
    'YOLO-L-WORLD':    'checkpoints/yolov8l-world.pt',
    'YOLO-X-WORLD':    'checkpoints/yolov8x-world.pt',
    'YOLO-S-WORLD-v2': 'checkpoints/yolov8s-worldv2.pt',
    'YOLO-M-WORLD-v2': 'checkpoints/yolov8m-worldv2.pt',
    'YOLO-L-WORLD-v2': 'checkpoints/yolov8l-worldv2.pt',
    'YOLO-X-WORLD-v2': 'checkpoints/yolov8x-worldv2.pt',
}

YOLO_GLOBAL_MODELS = {
    # Detection models
    'YOLO-N':              'checkpoints/yolo_global/yolo11n.pt',
    'YOLO-N-GAM':          'checkpoints/yolo_global/yolo11n-gam.pt',
    'YOLO-N-GAM-BBONE':    'checkpoints/yolo_global/yolo11n-gam-bbone.pt',
    'YOLO-N-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11n-simam-bbone.pt',
    'YOLO-N-SIMAM-MIN':    'checkpoints/yolo_global/yolo11n-simam-min.pt',
    'YOLO-N-SIMAM-FULL':   'checkpoints/yolo_global/yolo11n-simam-full.pt',
    'YOLO-N-MPDIOU':       'checkpoints/yolo_global/yolo11n-mpdiou.pt',
    'YOLO-S':              'checkpoints/yolo_global/yolo11s.pt',
    'YOLO-S-GAM':          'checkpoints/yolo_global/yolo11s-gam.pt',
    'YOLO-S-GAM-BBONE':    'checkpoints/yolo_global/yolo11s-gam-bbone.pt',
    'YOLO-S-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11s-simam-bbone.pt',
    'YOLO-S-SIMAM-MIN':    'checkpoints/yolo_global/yolo11s-simam-min.pt',
    'YOLO-S-SIMAM-FULL':   'checkpoints/yolo_global/yolo11s-simam-full.pt',
    'YOLO-S-MPDIOU':       'checkpoints/yolo_global/yolo11s-mpdiou.pt',
    'YOLO-M':              'checkpoints/yolo_global/yolo11m.pt',
    'YOLO-M-GAM':          'checkpoints/yolo_global/yolo11m-gam.pt',
    'YOLO-M-GAM-BBONE':    'checkpoints/yolo_global/yolo11m-gam-bbone.pt',
    'YOLO-M-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11m-simam-bbone.pt',
    'YOLO-M-SIMAM-MIN':    'checkpoints/yolo_global/yolo11m-simam-min.pt',
    'YOLO-M-SIMAM-FULL':   'checkpoints/yolo_global/yolo11m-simam-full.pt',
    'YOLO-M-MPDIOU':       'checkpoints/yolo_global/yolo11m-mpdiou.pt',
    'YOLO-L':              'checkpoints/yolo_global/yolo11l.pt',
    'YOLO-L-GAM':          'checkpoints/yolo_global/yolo11l-gam.pt',
    'YOLO-L-GAM-BBONE':    'checkpoints/yolo_global/yolo11l-gam-bbone.pt',
    'YOLO-L-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11l-simam-bbone.pt',
    'YOLO-L-SIMAM-MIN':    'checkpoints/yolo_global/yolo11l-simam-min.pt',
    'YOLO-L-SIMAM-FULL':   'checkpoints/yolo_global/yolo11l-simam-full.pt',
    'YOLO-L-MPDIOU':       'checkpoints/yolo_global/yolo11l-mpdiou.pt',
    'YOLO-X':              'checkpoints/yolo_global/yolo11x.pt',
    'YOLO-X-GAM':          'checkpoints/yolo_global/yolo11x-gam.pt',
    'YOLO-X-GAM-BBONE':    'checkpoints/yolo_global/yolo11x-gam-bbone.pt',
    'YOLO-X-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11x-simam-bbone.pt',
    'YOLO-X-SIMAM-MIN':    'checkpoints/yolo_global/yolo11x-simam-min.pt',
    'YOLO-X-SIMAM-FULL':   'checkpoints/yolo_global/yolo11x-simam-full.pt',
    'YOLO-X-MPDIOU':       'checkpoints/yolo_global/yolo11x-mpdiou.pt',

    # Segmentation models
    'YOLO-SEG-N':              'checkpoints/yolo_global/yolo11n-seg.pt',
    'YOLO-SEG-N-GAM':          'checkpoints/yolo_global/yolo11n-gam-seg.pt',
    'YOLO-SEG-N-GAM-BBONE':    'checkpoints/yolo_global/yolo11n-gam-bbone-seg.pt',
    'YOLO-SEG-N-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11n-simam-bbone-seg.pt',
    'YOLO-SEG-N-SIMAM-MIN':    'checkpoints/yolo_global/yolo11n-simam-min-seg.pt',
    'YOLO-SEG-N-SIMAM-FULL':   'checkpoints/yolo_global/yolo11n-simam-full-seg.pt',
    'YOLO-SEG-S':              'checkpoints/yolo_global/yolo11s-seg.pt',
    'YOLO-SEG-S-GAM':          'checkpoints/yolo_global/yolo11s-gam-seg.pt',
    'YOLO-SEG-S-GAM-BBONE':    'checkpoints/yolo_global/yolo11s-gam-bbone-seg.pt',
    'YOLO-SEG-S-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11s-simam-bbone-seg.pt',
    'YOLO-SEG-S-SIMAM-MIN':    'checkpoints/yolo_global/yolo11s-simam-min-seg.pt',
    'YOLO-SEG-S-SIMAM-FULL':   'checkpoints/yolo_global/yolo11s-simam-full-seg.pt',
    'YOLO-SEG-M':              'checkpoints/yolo_global/yolo11m-seg.pt',
    'YOLO-SEG-M-GAM':          'checkpoints/yolo_global/yolo11m-gam-seg.pt',
    'YOLO-SEG-M-GAM-BBONE':    'checkpoints/yolo_global/yolo11m-gam-bbone-seg.pt',
    'YOLO-SEG-M-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11m-simam-bbone-seg.pt',
    'YOLO-SEG-M-SIMAM-MIN':    'checkpoints/yolo_global/yolo11m-simam-min-seg.pt',
    'YOLO-SEG-M-SIMAM-FULL':   'checkpoints/yolo_global/yolo11m-simam-full-seg.pt',
    'YOLO-SEG-L':              'checkpoints/yolo_global/yolo11l-seg.pt',
    'YOLO-SEG-L-GAM':          'checkpoints/yolo_global/yolo11l-gam-seg.pt',
    'YOLO-SEG-L-GAM-BBONE':    'checkpoints/yolo_global/yolo11l-gam-bbone-seg.pt',
    'YOLO-SEG-L-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11l-simam-bbone-seg.pt',
    'YOLO-SEG-L-SIMAM-MIN':    'checkpoints/yolo_global/yolo11l-simam-min-seg.pt',
    'YOLO-SEG-L-SIMAM-FULL':   'checkpoints/yolo_global/yolo11l-simam-full-seg.pt',
    'YOLO-SEG-X':              'checkpoints/yolo_global/yolo11x-seg.pt',
    'YOLO-SEG-X-GAM':          'checkpoints/yolo_global/yolo11x-gam-seg.pt',
    'YOLO-SEG-X-GAM-BBONE':    'checkpoints/yolo_global/yolo11x-gam-bbone-seg.pt',
    'YOLO-SEG-X-SIMAM-BBONE':  'checkpoints/yolo_global/yolo11x-simam-bbone-seg.pt',
    'YOLO-SEG-X-SIMAM-MIN':    'checkpoints/yolo_global/yolo11x-simam-min-seg.pt',
    'YOLO-SEG-X-SIMAM-FULL':   'checkpoints/yolo_global/yolo11x-simam-full-seg.pt',
}

SAM_MODELS = {
    'SAM-T':     'checkpoints/sam2_t.pt',
    'SAM-S':     'checkpoints/sam2_s.pt',
    'SAM-B':     'checkpoints/sam2_b.pt',
    'SAM-L':     'checkpoints/sam2_l.pt',
    'SAM-2.1-T': 'checkpoints/sam2.1_t.pt',
    'SAM-2.1-S': 'checkpoints/sam2.1_s.pt',
    'SAM-2.1-B': 'checkpoints/sam2.1_b.pt',
    'SAM-2.1-L': 'checkpoints/sam2.1_l.pt'
}

DETECTION = "detection"
SEGMENTATION = "segmentation"
